Add binding for DAOS
chel-data/chel-fs pull request #23
Opened 2024-07-05 05:46 UTC by paul356

close #19

2024-07-05 05:47 UTC, paul356 commented on src/bindings/daos.rs
This is generated code by bindgen cli.

2024-07-05 07:55 UTC, josephaug26 requested changes

2024-07-05 07:55 UTC, josephaug26 commented on src/bindings/daos.rs
Since this is auto-generated can we have this not pushed to git. But Rather have a script to build which have this step. 
The script will
1. check if DAOS Client is installed.
           If not install it 
2. then do the bind-gen to generate this,

2024-07-06 07:52 UTC, josephaug26 approved these changes

2024-07-06 07:52 UTC, merged